/**
 * schedule_all_with_login.cjs
 * ===========================
 * Launches Chrome, logs into LinkedIn, and schedules ALL 7 posts:
 *   - 4 {{AUTHOR_NAME}} personal LinkedIn posts
 *   - 3 {{BRAND_SHORT_NAME}} company LinkedIn posts
 *
 * Reads from posts_today.json (generated by generate_all_content_gemini.py).
 *
 * Usage: node schedule_all_with_login.cjs
 */

const puppeteer = require('puppeteer-core');
const fs = require('fs');
const path = require('path');

// ============================================================
// CREDENTIALS
// ============================================================
const LINKEDIN_EMAIL = 'ahmed97028@gmail.com';
const LINKEDIN_PASSWORD = 'ahmedmughal4594';

// {{BRAND_SHORT_NAME}} company page URL
const ECOTRUSTIA_PAGE = 'https://www.linkedin.com/company/105396729/admin/page-posts/published/';

// ============================================================
// PUPPETEER SHADOW DOM HELPERS
// ============================================================
async function getElementShadow(page, selector) {
  const handle = await page.evaluateHandle((sel) => {
    function findEl(root) {
      if (!root) return null;
      const el = root.querySelector(sel);
      if (el) return el;
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT, null, false);
      let node;
      while (node = walker.nextNode()) {
        if (node.shadowRoot) {
          const found = findEl(node.shadowRoot);
          if (found) return found;
        }
      }
      return null;
    }
    return findEl(document.body);
  }, selector);
  return handle.asElement();
}

async function waitForSelectorShadow(page, selector, timeout = 15000) {
  const start = Date.now();
  while (Date.now() - start < timeout) {
    const el = await getElementShadow(page, selector);
    if (el) { await el.dispose(); return true; }
    await new Promise(r => setTimeout(r, 500));
  }
  throw new Error(`Timeout waiting for: ${selector}`);
}

async function clickNativelyShadow(page, finderFn) {
  try {
    await page.evaluate(() => {
      document.querySelectorAll('.msg-overlay-container,[class*="msg-overlay"],#msg-overlay')
        .forEach(el => el.remove());
    });
    const handle = await page.evaluateHandle((finder) => {
      const fn = new Function('return ' + finder)();
      function findInShadow(root) {
        if (!root) return null;
        const res = fn(root);
        if (res) return res;
        const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT, null, false);
        let node;
        while (node = walker.nextNode()) {
          if (node.shadowRoot) {
            const found = findInShadow(node.shadowRoot);
            if (found) return found;
          }
        }
        return null;
      }
      return findInShadow(document.body);
    }, finderFn.toString());

    const el = handle.asElement();
    if (el) {
      try {
        await page.evaluate(e => { e.focus(); e.scrollIntoView({ block: 'center' }); }, el);
        await new Promise(r => setTimeout(r, 200));
        await el.click();
      } catch {
        await page.evaluate(e => {
          const rect = e.getBoundingClientRect();
          const x = rect.left + rect.width / 2, y = rect.top + rect.height / 2;
          const opts = { bubbles: true, cancelable: true, view: window, clientX: x, clientY: y };
          e.dispatchEvent(new MouseEvent('mousedown', opts));
          e.focus();
          e.dispatchEvent(new MouseEvent('mouseup', opts));
          e.dispatchEvent(new MouseEvent('click', opts));
        }, el);
      }
      await el.dispose();
      return true;
    }
    return false;
  } catch (err) {
    console.error('clickNativelyShadow error:', err.message);
    return false;
  }
}

async function clickNativelyShadowRetry(page, finderFn, timeout = 15000) {
  const start = Date.now();
  while (Date.now() - start < timeout) {
    if (await clickNativelyShadow(page, finderFn)) return true;
    await new Promise(r => setTimeout(r, 1000));
  }
  return false;
}

async function fillFieldShadow(page, selector, value) {
  const el = await getElementShadow(page, selector);
  if (!el) throw new Error(`Cannot find field: ${selector}`);
  await page.evaluate(input => { input.focus(); input.select(); }, el);
  await new Promise(r => setTimeout(r, 400));
  await page.keyboard.press('Backspace');
  await new Promise(r => setTimeout(r, 400));
  await page.keyboard.type(value, {delay: 100});
  await page.keyboard.press('Enter');
  await new Promise(r => setTimeout(r, 200));
  await page.keyboard.press('Escape');
  await new Promise(r => setTimeout(r, 200));
  await page.keyboard.press('Tab');
  await el.dispose();
  await new Promise(r => setTimeout(r, 800));
}

async function fillTimeCombobox(page, selector, value) {
  const el = await getElementShadow(page, selector);
  if (!el) throw new Error(`Cannot find time combobox: ${selector}`);
  await page.evaluate(input => { input.focus(); input.select(); }, el);
  await new Promise(r => setTimeout(r, 400));
  await page.keyboard.press('Backspace');
  await new Promise(r => setTimeout(r, 400));
  await page.keyboard.type(value, {delay: 100});
  await new Promise(r => setTimeout(r, 1500));
  await page.keyboard.press('ArrowDown');
  await new Promise(r => setTimeout(r, 400));
  await page.keyboard.press('Enter');
  await el.dispose();
  await new Promise(r => setTimeout(r, 800));
}

const sleep = ms => new Promise(r => setTimeout(r, ms));

// ============================================================
// MAIN
// ============================================================
(async () => {
  // Load posts
  const postsFile = path.resolve(__dirname, 'posts_today.json');
  if (!fs.existsSync(postsFile)) {
    console.error('ERROR: posts_today.json not found. Run generate_all_content_gemini.py first.');
    process.exit(1);
  }
  const postsData = JSON.parse(fs.readFileSync(postsFile, 'utf8'));
  const ahmedPosts = postsData.ahmed_linkedin || [];
  const ecoPosts = postsData.{{BRAND_SHORT_NAME_LOWER}}_linkedin || [];

  console.log(`\n${'='.repeat(60)}`);
  console.log(`LINKEDIN SCHEDULING WITH LOGIN — ${postsData.date}`);
  console.log(`Posts scheduled for: ${postsData.schedule_date}`);
  console.log(`{{AUTHOR_NAME}}: ${ahmedPosts.length} posts | {{BRAND_SHORT_NAME}}: ${ecoPosts.length} posts`);
  console.log('='.repeat(60));

  // Resolve asset paths
  for (const post of ahmedPosts) {
    if (post.type === 'carousel') {
      const dir = post.carousel_pdf;
      if (dir && fs.existsSync(dir)) {
        const pdfs = fs.readdirSync(dir).filter(f => f.endsWith('.pdf'));
        if (pdfs.length > 0) {
          post.assetPath = path.resolve(dir, pdfs[pdfs.length - 1]);
          post.title = post.carousel_title || '{{AUTHOR_NAME}} Builder Breakdown';
        }
      }
      if (!post.assetPath) {
        console.warn(`⚠ Carousel PDF not found. Post ${post.id} will be text-only.`);
        post.type = 'text';
      }
    } else if (post.type === 'infographic' || post.type === 'image') {
      const fn = post.infographic_png || post.image_png;
      if (fn && fs.existsSync(fn)) {
        post.assetPath = path.resolve(fn);
      } else {
        console.warn(`⚠ Media not found: ${fn}. Post ${post.id} will be text-only.`);
        post.type = 'text';
      }
    }
  }

  for (const post of ecoPosts) {
    if (post.type === 'carousel') {
      const dir = post.carousel_pdf;
      if (dir && fs.existsSync(dir)) {
        const pdfs = fs.readdirSync(dir).filter(f => f.endsWith('.pdf'));
        if (pdfs.length > 0) {
          post.assetPath = path.resolve(dir, pdfs[pdfs.length - 1]);
          post.title = post.carousel_title || '{{BRAND_NAME}}';
        }
      }
      if (!post.assetPath) {
        console.warn(`⚠ Carousel PDF not found. Post ${post.id} will be text-only.`);
        post.type = 'text';
      }
    } else if (post.type === 'infographic' || post.type === 'image') {
      const fn = post.infographic_png || post.image_png;
      if (fn && fs.existsSync(fn)) {
        post.assetPath = path.resolve(fn);
      } else {
        console.warn(`⚠ Media not found: ${fn}. Post ${post.id} will be text-only.`);
        post.type = 'text';
      }
    }
  }

  const screenshotDir = path.resolve(__dirname, 'slack_downloads');
  if (!fs.existsSync(screenshotDir)) fs.mkdirSync(screenshotDir, { recursive: true });

  // ========== LAUNCH CHROME & LOGIN ==========
  console.log('\nLaunching Chrome browser...');
  const browser = await puppeteer.launch({
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    headless: false,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-gpu',
      '--disable-dev-shm-usage',
      '--use-mock-keychain',
      '--password-store=basic',
      '--disable-extensions',
      '--window-size=1280,1200',
      '--lang=en-US',
      '--accept-lang=en-US,en'
    ],
    defaultViewport: { width: 1280, height: 1200 }
  });

  const page = (await browser.pages())[0];

  // Set English language headers
  await page.setExtraHTTPHeaders({
    'Accept-Language': 'en-US,en;q=0.9'
  });

  // Navigate to English login page
  console.log('Navigating to LinkedIn login (English)...');
  await page.goto('https://www.linkedin.com/login?lang=en', { waitUntil: 'networkidle2', timeout: 30000 });
  await sleep(3000);

  await page.screenshot({ path: path.resolve(__dirname, 'login_debug.png') });
  console.log('Login page screenshot saved to login_debug.png');

  // Check if already logged in
  let currentUrl = page.url();
  console.log('Current URL:', currentUrl);

  if (currentUrl.includes('/feed')) {
    console.log('Already logged in!');
  } else {
    console.log('Entering credentials...');
    
    // Clear and type email
    console.log('Typing email...');
    const emailHandle = await page.evaluateHandle(() => {
        return Array.from(document.querySelectorAll('input[type="email"], input[type="text"], #username'))
            .find(el => el.offsetParent !== null);
    });
    
    // Check if the handle actually points to an element
    const isEmailElement = await page.evaluate(e => e instanceof HTMLElement, emailHandle);
    
    if (isEmailElement) {
      try {
        await emailHandle.click({ clickCount: 3 });
        await page.keyboard.press('Backspace');
        await emailHandle.type(LINKEDIN_EMAIL, { delay: 30 });
        console.log('Email typed.');
      } catch (e) {
        console.log('Error typing email:', e.message);
      }
    } else {
      console.log('Visible email field not found!');
    }
    
    // Clear and type password
    console.log('Typing password...');
    const passHandle = await page.evaluateHandle(() => {
        return Array.from(document.querySelectorAll('input[type="password"], #password'))
            .find(el => el.offsetParent !== null);
    });
    
    const isPassElement = await page.evaluate(e => e instanceof HTMLElement, passHandle);
    
    if (isPassElement) {
      try {
        await passHandle.click({ clickCount: 3 });
        await page.keyboard.press('Backspace');
        await passHandle.type(LINKEDIN_PASSWORD, { delay: 30 });
        console.log('Password typed.');
      } catch (e) {
        console.log('Error typing password:', e.message);
      }
    } else {
      console.log('Visible password field not found!');
    }

    await page.screenshot({ path: path.resolve(__dirname, 'login_filled_debug.png') });
    console.log('Saved filled login screenshot');

    // Click sign in button
    console.log('Clicking Sign in...');
    const submitted = await page.evaluate(() => {
      // Try submit button (works for both English and Arabic)
      const btn = document.querySelector('button[type="submit"]') ||
                  document.querySelector('[data-litms-control-urn*="login-submit"]') ||
                  [...document.querySelectorAll('button')].find(b => 
                    b.textContent.trim().toLowerCase().includes('sign in') ||
                    b.textContent.includes('تسجيل الدخول')
                  );
      if (btn) { 
        console.log('Found submit button:', btn.textContent.trim());
        btn.click(); 
        return true; 
      }
      return false;
    });
    
    if (!submitted) {
      console.log('No submit button found, pressing Enter...');
      await page.keyboard.press('Enter');
    }
    
    console.log('Waiting for login to complete...');
    await sleep(8000);

    // Check post-login state
    currentUrl = page.url();
    console.log('Post-login URL:', currentUrl);
    await page.screenshot({ path: path.resolve(__dirname, 'post_login_debug.png') });

    if (currentUrl.includes('challenge') || currentUrl.includes('checkpoint')) {
      console.log('\n⚠️  Security challenge detected!');
      console.log('Please complete the challenge manually in the Chrome window.');
      console.log('Waiting 90 seconds...\n');
      await sleep(90000);
      currentUrl = page.url();
      console.log('URL after challenge wait:', currentUrl);
    }

    if (currentUrl.includes('login') || currentUrl.includes('signup') || currentUrl.includes('join')) {
      console.log('\n⚠️  Login appears to have FAILED.');
      console.log('Current URL:', currentUrl);
      console.log('Please log in manually in the Chrome window.');
      console.log('Waiting 60 seconds for manual login...\n');
      await sleep(60000);
      currentUrl = page.url();
      console.log('URL after manual login wait:', currentUrl);
      
      if (currentUrl.includes('login') || currentUrl.includes('signup') || currentUrl.includes('join')) {
        console.error('ERROR: Still not logged in. Cannot proceed with scheduling.');
        console.log('Please close Chrome and try again.');
        // Don't close browser — let user see the state
        process.exit(1);
      }
    }
  }

  console.log('✓ Login successful! Navigating to feed...');
  try {
    await page.goto('https://www.linkedin.com/feed/', { waitUntil: 'domcontentloaded', timeout: 15000 });
  } catch (e) {
    console.warn('Navigation timeout — continuing:', e.message);
  }
  await sleep(5000);

  // Verify we're on the feed
  currentUrl = page.url();
  console.log('Feed URL:', currentUrl);
  await page.screenshot({ path: path.resolve(__dirname, 'feed_debug.png') });
  
  // Check for "Start a post" button presence
  let feedReady = false;
  try {
    feedReady = await page.evaluate(() => {
      const allText = document.body.innerText || '';
      return allText.includes('Start a post') || allText.includes('ابدأ منشورًا');
    });
  } catch(e) {
    console.warn('Could not check feed text:', e.message);
  }
  console.log('Feed has "Start a post" button:', feedReady);

  // Hide messaging overlays
  await page.evaluate(() => {
    const s = document.createElement('style');
    s.innerHTML = `.msg-overlay-container,[class*="msg-overlay"],#msg-overlay{display:none!important}`;
    document.head.appendChild(s);
  });

  // ============================================================
  // HELPER: Schedule a single post
  // ============================================================
  async function schedulePost(post, label, navigateUrl) {
    const prefix = `${screenshotDir}/${label}_post_${post.id}_${post.type}`;
    console.log(`\n${'─'.repeat(50)}`);
    console.log(`${label} Post ${post.id} | ${post.type} | ${post.slot}`);
    console.log('─'.repeat(50));

    // Navigate
    console.log(`Navigating to ${navigateUrl}...`);
    try {
      await page.goto(navigateUrl, { waitUntil: 'domcontentloaded', timeout: 15000 });
    } catch (e) {
      console.log('Navigation timeout — continuing:', e.message);
    }
    await sleep(5000); // Give more time for the page to fully load

    // Hide messaging overlays
    await page.evaluate(() => {
      document.querySelectorAll('.msg-overlay-container,[class*="msg-overlay"],#msg-overlay')
        .forEach(el => el.remove());
    });

    // Close any open composer
    await page.evaluate(() => {
      const btn = Array.from(document.querySelectorAll('button')).find(b =>
        (b.getAttribute('aria-label') || '').includes('Dismiss') ||
        (b.innerText || '').includes('Dismiss')
      );
      if (btn) btn.click();
    });
    await sleep(1500);

    // Open post composer - try multiple approaches
    console.log("Clicking 'Start a post'...");
    
    // Approach 1: Shadow DOM search
    let started = await clickNativelyShadow(page, (root) =>
      Array.from(root.querySelectorAll('a[href*="sharebox"], button, div[role="button"]')).find(el =>
        (el.innerText || '').trim().includes('Start a post') ||
        (el.getAttribute('href') || '').includes('sharebox') ||
        (el.innerText || '').trim().includes('ابدأ منشورًا')
      )
    );

    // Approach 2: Direct selector click
    if (!started) {
      console.log('Shadow DOM approach failed. Trying direct selectors...');
      started = await page.evaluate(() => {
        // Try the share box trigger button
        const trigger = document.querySelector('button.share-box-feed-entry__trigger');
        if (trigger) { trigger.click(); return true; }
        
        // Try any button/link with "Start a post" text
        const allBtns = [...document.querySelectorAll('button, a, div[role="button"]')];
        const postBtn = allBtns.find(b => {
          const text = (b.innerText || b.textContent || '').trim();
          return text.includes('Start a post') || text.includes('ابدأ منشورًا');
        });
        if (postBtn) { postBtn.click(); return true; }
        
        // Try clicking the share box area directly
        const shareBox = document.querySelector('.share-box-feed-entry__top-bar, .share-box');
        if (shareBox) { shareBox.click(); return true; }
        
        return false;
      });
    }

    // Approach 3: Click on the "What do you want to talk about?" / post input area
    if (!started) {
      console.log('Trying post input area...');
      started = await page.evaluate(() => {
        const inputs = [...document.querySelectorAll('[role="textbox"], [contenteditable="true"], .share-box-feed-entry__closed-share-box')];
        for (const el of inputs) {
          if (el.offsetParent !== null) {
            el.click();
            return true;
          }
        }
        return false;
      });
    }

    if (!started) {
      // Take debug screenshot
      await page.screenshot({ path: `${prefix}_cant_find_start.png` });
      
      // Log all visible buttons for debugging
      const btns = await page.evaluate(() => {
        return [...document.querySelectorAll('button, a[role="button"]')].slice(0, 30).map(b => ({
          tag: b.tagName,
          text: (b.innerText || '').trim().substring(0, 60),
          ariaLabel: b.getAttribute('aria-label') || '',
          class: (b.className || '').substring(0, 60)
        }));
      });
      console.log('Available buttons on page:', JSON.stringify(btns, null, 2));
      throw new Error("Could not find 'Start a post' button");
    }

    const editorSelector = '.ql-editor,[contenteditable="true"]';
    await waitForSelectorShadow(page, editorSelector, 15000);
    await sleep(1000);

    // Handle file uploads (carousel, infographic, image)
    if ((post.type === 'carousel' || post.type === 'infographic' || post.type === 'image') && post.assetPath) {
      console.log(`Attaching ${post.type}: ${path.basename(post.assetPath)}...`);

      let clickedAdd = false;

      if (post.type === 'infographic' || post.type === 'image') {
        clickedAdd = await clickNativelyShadow(page, (root) => {
          const btns = Array.from(root.querySelectorAll('button'));
          return btns.find(b => {
             const lbl = (b.ariaLabel || b.innerText || '').toLowerCase();
             return lbl.includes('media') || lbl.includes('image') || lbl.includes('photo');
          });
        });
      } else if (post.type === 'carousel') {
        clickedAdd = await clickNativelyShadow(page, (root) => {
          const btns = Array.from(root.querySelectorAll('button'));
          return btns.find(b => (b.ariaLabel || '').includes('Add a document')) ||
                 btns.find(b => (b.innerText || '').toLowerCase().includes('document'));
        });
        if (!clickedAdd) {
          await clickNativelyShadow(page, (root) =>
            Array.from(root.querySelectorAll('button')).find(b =>
              (b.ariaLabel || '').includes('More') || (b.innerText || '').includes('More')
            )
          );
          await sleep(1200);
          clickedAdd = await clickNativelyShadow(page, (root) => {
            const btns = Array.from(root.querySelectorAll('button'));
            return btns.find(b => (b.ariaLabel || '').includes('Add a document')) ||
                   btns.find(b => (b.innerText || '').toLowerCase().includes('document'));
          });
        }
      }

      if (!clickedAdd) throw new Error(`Could not find upload button for ${post.type}`);
      await sleep(8000);

      // Find and use file input
      const fileInputHandle = await page.evaluateHandle(() => {
        function find(root) {
          const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT, null, false);
          let node;
          while (node = walker.nextNode()) {
            if (node.tagName === 'INPUT' && node.type === 'file') return node;
            if (node.shadowRoot) { const f = find(node.shadowRoot); if (f) return f; }
          }
          return null;
        }
        return find(document.body);
      });
      const fileInput = fileInputHandle.asElement();
      if (!fileInput) throw new Error('File input not found');
      await fileInput.uploadFile(post.assetPath);
      console.log('File uploaded. Waiting...');
      await sleep(5000);

      // Set carousel title if needed
      if (post.type === 'carousel') {
        try {
          await waitForSelectorShadow(page, 'input[placeholder*="title"]', 10000);
          const titleInput = await getElementShadow(page, 'input[placeholder*="title"]');
          if (titleInput) {
            await titleInput.focus();
            await page.keyboard.type(post.title || 'Builder Breakdown');
            await titleInput.dispose();
          }
        } catch (e) {
          console.log('No title input found, continuing...');
        }
      }

      // Click Done
      await clickNativelyShadowRetry(page, (root) =>
        Array.from(root.querySelectorAll('button')).find(b => {
          const txt = (b.innerText || '').trim();
          return (txt === 'Done' || txt === 'Next') && !b.disabled && !b.className.includes('vjs-');
        })
      );
      await sleep(3000);
    }

    // Fill caption
    console.log('Typing caption...');
    await waitForSelectorShadow(page, editorSelector, 15000);
    const editorEl = await getElementShadow(page, editorSelector);
    await editorEl.focus();
    await page.evaluate(el => {
      el.focus();
      document.execCommand('selectAll', false, null);
      document.execCommand('delete', false, null);
    }, editorEl);
    await sleep(800);

    const paragraphs = post.caption.split('\n');
    for (let i = 0; i < paragraphs.length; i++) {
      if (i > 0) { await page.keyboard.press('Enter'); await sleep(120); }
      if (paragraphs[i]) { await page.keyboard.type(paragraphs[i]); await sleep(120); }
    }
    await sleep(1500);
    await editorEl.dispose();
    await page.screenshot({ path: `${prefix}_draft.png` });

    if (post.post_now) {
      // ── POST IMMEDIATELY ──
      console.log('Posting immediately (post_now=true)...');
      const clickedPost = await clickNativelyShadow(page, (root) => {
        const modal = root.querySelector('.share-box,.artdeco-modal,[role="dialog"]');
        const container = modal || root;
        const buttons = Array.from(container.querySelectorAll('button'));
        return buttons.find(b => (b.innerText || '').trim() === 'Post' && !b.disabled);
      });
      if (!clickedPost) throw new Error('Could not find Post button for immediate post');
      console.log('Waiting for post confirmation...');
      await sleep(8000);
      console.log(`✓ ${label} Post ${post.id} POSTED IMMEDIATELY`);
    } else {
      // ── SCHEDULE ──
      console.log('Opening schedule modal...');
      const clickedSched = await clickNativelyShadow(page, (root) => {
        const modal = root.querySelector('.share-box,.artdeco-modal,[role="dialog"]');
        const container = modal || root;
        const buttons = Array.from(container.querySelectorAll('button'));
        const postBtn = buttons.find(b => (b.innerText || '').trim() === 'Post');
        if (postBtn && postBtn.previousElementSibling) return postBtn.previousElementSibling;
        return buttons.find(b => (b.ariaLabel || '').includes('Schedule'));
      });
      if (!clickedSched) throw new Error('Could not find Schedule icon button');
      await sleep(2500);

      // Set date and time
      console.log(`Setting date: ${post.date}, time: ${post.slot}`);
      await fillFieldShadow(page,
        'input[placeholder*="Date"],input[aria-label*="date"],input[id*="date"]', post.date);

      // Normalize time: LinkedIn expects e.g. "3:00 AM" not "03:00 AM"
      let t = post.slot;
      if (t.startsWith('0')) t = t.substring(1);
      await fillTimeCombobox(page,
        'input[placeholder*="Time"],input[aria-label*="time"],input[id*="time"],input[role="combobox"]', t);

      await page.screenshot({ path: `${prefix}_schedule.png` });

      // Click Next
      const clickedNext = await clickNativelyShadow(page, (root) =>
        Array.from(root.querySelectorAll('button')).find(b => (b.innerText || '').trim() === 'Next')
      );
      if (!clickedNext) throw new Error('Could not click Next');
      await sleep(2500);

      // Click Schedule (final)
      const clickedFinal = await clickNativelyShadow(page, (root) =>
        Array.from(root.querySelectorAll('button')).find(b => (b.innerText || '').trim() === 'Schedule')
      );
      if (!clickedFinal) throw new Error('Could not click final Schedule button');

      console.log('Waiting for confirmation...');
      await sleep(6000);
      console.log(`✓ ${label} Post ${post.id} scheduled for ${post.date} at ${post.slot}`);
    }
  }

  // ============================================================
  // SCHEDULE AHMED'S 4 POSTS
  // ============================================================
  console.log(`\n${'='.repeat(60)}`);
  console.log(`SCHEDULING AHMED PERSONAL — ${ahmedPosts.length} posts`);
  console.log('='.repeat(60));

  for (const post of ahmedPosts) {
    try {
      await schedulePost(post, 'ahmed', 'https://www.linkedin.com/feed/');
    } catch (err) {
      console.error(`✗ ERROR on {{AUTHOR_NAME}} Post ${post.id}: ${err.message}`);
      try { await page.screenshot({ path: `${screenshotDir}/ahmed_post_${post.id}_error.png` }); } catch(_) {}
      await page.keyboard.press('Escape');
      await sleep(1000);
    }
  }

  // ============================================================
  // SCHEDULE ECOTRUSTIA'S 3 POSTS (Company Page)
  // ============================================================
  console.log(`\n${'='.repeat(60)}`);
  console.log(`SCHEDULING ECOTRUSTIA LINKEDIN — ${ecoPosts.length} posts`);
  console.log('='.repeat(60));

  for (const post of ecoPosts) {
    try {
      await schedulePost(post, '{{BRAND_SHORT_NAME_LOWER}}', ECOTRUSTIA_PAGE);
    } catch (err) {
      console.error(`✗ ERROR on {{BRAND_SHORT_NAME}} Post ${post.id}: ${err.message}`);
      try { await page.screenshot({ path: `${screenshotDir}/eco_post_${post.id}_error.png` }); } catch(_) {}
      await page.keyboard.press('Escape');
      await sleep(1000);
    }
  }

  // ============================================================
  // DONE
  // ============================================================
  console.log(`\n${'='.repeat(60)}`);
  console.log('✅ ALL LINKEDIN POSTS SCHEDULING COMPLETE');
  console.log(`   {{AUTHOR_NAME}}: ${ahmedPosts.length} posts`);
  console.log(`   {{BRAND_SHORT_NAME}}: ${ecoPosts.length} posts`);
  console.log(`   Scheduled for: ${postsData.schedule_date}`);
  console.log('='.repeat(60));
  console.log('The browser will remain open for you to verify.');
  console.log('Close it manually when done.');

})();
